export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AFTER_LOGIN_REDIRECT_TO = 'AFTER_LOGIN_REDIRECT_TO';
export const GET_AUTH_DETAILS = 'GET_AUTH_DETAILS';
export const AUTO_LOGIN_INITIATE = 'AUTO_LOGIN_INITIATE';

export const FETCH_QUESTION_START = 'FETCH_QUESTION_START';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAIL = 'FETCH_QUESTION_FAIL';