export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AFTER_LOGIN_REDIRECT_TO = 'AFTER_LOGIN_REDIRECT_TO';
export const GET_AUTH_DETAILS = 'GET_AUTH_DETAILS';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const INSTRUCTOR_FETCH_START = 'INSTRUCTOR_FETCH_START';
export const INSTRUCTOR_FETCH_SUCCESS = 'INSTRUCTOR_FETCH_SUCCESS';
export const INSTRUCTOR_FETCH_FAIL = 'INSTRUCTOR_FETCH_FAIL';

export const COURSE_FETCH_START = 'COURSE_FETCH_START';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_FAIL = 'COURSE_FETCH_FAIL';