export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AFTER_LOGIN_REDIRECT_TO = 'AFTER_LOGIN_REDIRECT_TO';
export const GET_AUTH_DETAILS = 'GET_AUTH_DETAILS';
export const AUTO_LOGIN_INITIATE = 'AUTO_LOGIN_INITIATE';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const COURSE_CATEGORY_FETCHED_START = 'COURSE_CATEGORY_FETCHED_START';
export const COURSE_CATEGORY_FETCHED_SUCCESS = 'COURSE_CATEGORY_FETCHED_SUCCESS';
export const COURSE_CATEGORY_FETCHED_FAIL = 'COURSE_CATEGORY_FETCHED_FAIL';

export const MY_COURSES_FETCHED_START = 'MY_COURSES_FETCHED_START';
export const MY_COURSES_FETCHED_SUCCESS = 'MY_COURSES_FETCHED_SUCCESS';
export const MY_COURSES_FETCHED_FAIL = 'MY_COURSES_FETCHED_FAIL';